import React from 'react';

export default function LegalTermsContentEN() {
  return (
    <div className="relative overflow-hidden py-16">
      <div className="relative px-4 sm:px-6 lg:px-8">
        <div className="prose-elbwalker prose prose-lg mx-auto mt-6 text-gray-400">
          <h3 className="text-gray-50">1. Scope / General </h3>
          <p>
            1.1 For the business relationship between elbwalker GmbH,
            Bernstorffstraße 118, 22767 Hamburg (hereinafter referred to as
            elbwalker), and the customer (hereinafter referred to as user), the
            following General Terms of Use apply exclusively in the version
            valid at the time the contract was concluded. Deviating conditions
            of the user or third parties are not recognized unless elbwalker
            expressly agrees to their validity in writing.
          </p>
          <p>
            1.2 Unless otherwise agreed, the terms of use apply in the version
            communicated as a framework agreement also for similar future
            contracts without elbwalker having to refer to them separately.
          </p>
          <p>
            1.3 The service offer under the domain www.elbwalker.com is aimed
            exclusively at users who have reached the age of 18, have full legal
            capacity and are entrepreneurs. “Entrepreneurs” in the sense of
            these terms of use are natural or legal persons or partnerships with
            legal capacity who, when concluding the contract, are exercising
            their commercial or independent professional activity.
          </p>
          <p>
            1.4 The contract language is German. In the event of contradictions
            between different language versions, the German language version is
            decisive.
          </p>
          <p>
            1.5 elbwalker is only a provider of elbwalker Analytics and has no
            economic or legal connection with the user's offer. elbwalker is
            neither a vicarious agent of the user nor a party to contracts
            concluded between the user and third parties.
          </p>
          <h3 className="text-gray-50">
            2. Object of service / conclusion of contract
          </h3>
          <p>
            2.1 elbwalker is a web service provider and operates a
            self-developed internet-based software solution that collects,
            stores and analyzes user interactions on websites and within
            applications as well as data migration via interfaces to and from
            third-party systems allowed (hereinafter referred to as elbwalker
            Analytics). The subject of this contract is the temporary provision
            of the software application hosted on servers of elbwalker or in
            data centers commissioned by elbwalker for the use of their
            functionalities via the Internet, the granting of corresponding
            mutual rights of use and the provision of storage space for those
            generated and generated by the user through the use of elbwalker
            Analytics / or the use of data required by elbwalker Analytics
            (hereinafter "application data") to the agreed extent against
            payment of the agreed fee. The specific functional scope of
            elbwalker Analytics results from the service description at
            www.elbwalker.com. The service description serves to present the
            service offered and does not constitute a guarantee.
          </p>
          <p>
            2.2 elbwalker's area of responsibility begins at the transfer point.
            The transfer point to elbwalker Analytics is the interface between
            the Internet medium and the elbwalker environment, which is hosted
            on the elbwalker servers or in the data centers used by elbwalker.
          </p>
          <p>
            2.3 elbwalker uses technologies from third-party providers as part
            of its services. The availability of these technologies is beyond
            the control of elbwalker. The provision of services by elbwalker is
            therefore subject to the technical and / or legal availability of
            third-party technologies.
          </p>
          <p>
            2.4 Registered users have the option of booking chargeable service
            packages (subscriptions). The user makes a selection of a service
            package. The scope of the service package results from the current
            price list (www.elbwalker.com/pricing). If the free 100,000 events
            per month are exceeded an the user accepts the terms of use, the
            user submits an offer to conclude a paid contract. The contract is
            concluded upon receipt of the confirmation email from elbwalker.
            From this point in time, elbwalker Analytics can be used within the
            scope of the contractually agreed usage.
          </p>
          <h3 className="text-gray-50">3. Availabilities</h3>
          <p>
            Insofar as we obtain your consent for the processing of personal
            data, Article 6 (1) (a) GDPR serves as the legal basis for the
            processing of personal data. When processing personal data that is
            necessary to fulfill a contract to which you are a party, Article 6
            (1) (b) GDPR serves as the legal basis. This also applies to
            processing operations that are necessary to carry out
            pre-contractual measures. If the processing of personal data is
            necessary to fulfill a legal obligation to which our company is
            subject, Article 6 (1) (c) GDPR serves as the legal basis If it is
            necessary to safeguard a legitimate interest of our company or a
            third party and if your interests, fundamental rights and freedoms
            do not outweigh the first-mentioned interest, Article 6 (1) (f) GDPR
            serves as the legal basis for processing.
          </p>
          <h3 className="text-gray-50">
            4. Legitimate interests in processing
          </h3>
          <p>
            4.1 elbwalker strives to make elbwalker Analytics fully available in
            addition to the application data. The availability of elbwalker
            Analytics is 98% on an annual average. In particular, for technical
            reasons, such as necessary maintenance and repair work, access to
            elbwalker Analytics may be temporarily restricted. Planned technical
            failures must be reported to the user at least 7 days in advance.
            elbwalker is not responsible for the services of third parties that
            are required for the use of elbwalker's services (e.g. internet
            access).
          </p>
          <p>
            4.2 If elbwalker is hindered in the execution of the order by a
            strike, lockout, official intervention or other circumstances
            through no fault of its own, delivery and service deadlines are
            considered to be extended by the duration of the hindrance and by an
            appropriate start-up time after the end of the hindrance. elbwalker
            will notify the user of the handicap; elbwalker is not in default
            for this period.
          </p>
          <p>
            4.3 Irrespective of the availability quota, elbwalker's liability
            remains in accordance with Section 10.3. and 10.4. of these terms of
            use unaffected.
          </p>
          <p>
            4.4 The user must report any disruptions immediately. The manner in
            which the fault is dealt with is at the discretion of elbwalker.
          </p>
          <h3 className="text-gray-50">
            5. Rights and obligations of elbwalker
          </h3>
          <p>
            5.1 elbwalker provides the user with elbwalker Analytics for a fee
            for the duration of the contractual relationship.
          </p>
          <p>
            5.2 elbwalker will provide, maintain and maintain the necessary
            technical server landscapes for the provision of the services. In
            this respect, elbwalker is entitled to use third-party companies as
            subcontractors.
          </p>
          <p>
            5.3 During the term of the usage contract, elbwalker backs up the
            data on the server with an up-to-date data backup medium on a daily
            basis. There is no contractual obligation to archive the data backup
            media. The user has no right to the surrender of the data backup
            medium.
          </p>
          <p>
            5.4 elbwalker is entitled to change and optimize elbwalker Analytics
            to the extent that the purpose of this contract is not significantly
            impaired or endangered. With regard to services offered free of
            charge, the elbwalker is entitled to discontinue these at any time
            without notice.
          </p>
          <p>
            5.5 elbwalker is entitled to use analyzes and application data
            generated via elbwalker Analytics in anonymous form to optimize and
            improve elbwalker Analytics and for marketing purposes. This also
            applies beyond the term of the contract.
          </p>
          <h3 className="text-gray-50">6. Rights and duties of the user</h3>
          <p>
            6.1 The user assures that the information provided by him is correct
            and complete. He will immediately inform elbwalker of any changes to
            the data required to execute the contract. He will only use
            elbwalker to the contractually agreed scope and fulfill all
            obligations necessary for the performance of this contract in a
            timely, complete and technically proper manner, in particular pay
            the agreed remuneration on time.
          </p>
          <p>6.2 The user will in particular..</p>
          <p>
            6.2.1. Keep the usage and access authorizations assigned to him or
            the users as well as agreed identification and authentication
            safeguards secret, protect them from access by third parties and do
            not pass them on to unauthorized users. These data are to be
            protected by suitable and customary measures. The user will inform
            the elbwalker immediately if there is a suspicion that the access
            data and / or passwords could have become known to unauthorized
            persons;
          </p>
          <p>6.2.2. create the agreed entry requirements;</p>
          <p>
            6.2.3. comply with the restrictions / obligations with regard to the
            rights of use according to section 6 of this contract, in particular
            a) no information or data is called up or allowed to be called up in
            an unauthorized manner, or programs operated by elbwalker are
            interfered with or allowed to intervene, or penetrate or encourage
            such penetration into elbwalker's data networks b) to comply with
            this contract;
          </p>
          <p>
            6.2.4. Obtain the necessary consent from the data subject, insofar
            as he collects, processes or uses personal data when using the
            software and no statutory permission applies;
          </p>
          <p>
            6.2.5. Before sending data and information to elbwalker Analytics,
            check them for viruses and use state-of-the-art virus protection
            programs;
          </p>
          <p>
            6.2.6. if he transmits elbwalker data to generate application data
            with the help of elbwalker Analytics, back it up regularly and
            according to the significance of the data and create his own backup
            copies in order to enable the reconstruction of the same if the data
            and information are lost;
          </p>
          <p>
            6.2.7. if and to the extent that the technical possibility is given
            to him by mutual agreement, regularly back up the application data
            stored on the server by downloading.
          </p>
          <p>
            6.3 The user must ensure that the necessary hardware and software
            for internet use and the necessary internet access are available and
            kept up to date. The provision of these requirements as well as the
            telecommunication services of the transmission services from the
            server to the devices used by the user are not the subject of this
            contract, but are the responsibility of the user.
          </p>
          <p>
            6.4 When using elbwalker Analytics, the user will observe all
            applicable laws and other legal provisions of the Federal Republic
            of Germany. The user is responsible for ensuring that elbwalker
            Analytics is not misused.
          </p>
          <p>
            6.5 The user will only assign his rights from this contract to third
            parties with the prior consent of elbwalker; Section 354 a of the
            German Commercial Code (HGB) remains unaffected.
          </p>
          <p>
            6.6 After blocking and / or termination by elbwalker, the user is
            prohibited from opening a new user account. User accounts are not
            transferable.
          </p>
          <h3 className="text-gray-50">7. Usage rights</h3>
          <p>
            7.1 The user and any employees he may be entitled to receive the
            non-exclusive right, limited in time to the term of the respective
            contract and subject to remuneration for chargeable services, to
            access elbwalker Analytics via telecommunications and to use the
            functionalities associated with elbwalker Analytics in accordance
            with this contract . The user does not receive any further rights,
            in particular to software applications, source codes or the
            operating software.
          </p>
          <p>
            7.2 The user is not entitled to use elbwalker Analytics beyond what
            is permitted under this contract. In particular, the user is not
            permitted to reproduce, sell or lend, rent or lend elbwalker
            Analytics or parts thereof for a limited period of time. The rights
            according to §§ 69 d, 69 e UrhG remain unaffected.
          </p>
          <p>
            7.3 If the user violates the regulations in Section 7.1. and 7.2.
            for reasons for which he is responsible, elbwalker can block the
            user's access to elbwalker Analytics after notifying the user in
            advance (at least in text form) if the violation can be proven to
            have been eliminated. If the user continues to violate or repeatedly
            violates the regulations in Section 7.1 despite a corresponding
            warning from elbwalker. and 7.2., and if he is responsible for this,
            the elbwalker can extraordinarily terminate the contract without
            observing a period of notice.
          </p>
          <p>
            7.4 In the event of a culpable and unauthorized transfer of use or
            use, the user has to pay elbwalker an immediately due contractual
            penalty in the amount of three times the monthly transfer price.
            elbwalker reserves the right to assert claims for damages. In this
            case, the contractual penalty will be offset against the claim for
            damages.
          </p>
          <p>
            7.5 If elbwalker provides new versions, updates, upgrades or other
            new deliveries with regard to elbwalker Analytics during the term,
            the above rights also apply to these.
          </p>
          <p>
            7.6 The user grants elbwalker, free of charge, the irrevocable,
            unrestricted right in terms of time, content and space to the
            application and analysis data generated by elbwalker Analytics at
            the time of their creation, to provide this data in anonymised form
            for their own purposes (including to improve and promote the
            software) to use.
          </p>
          <h3 className="text-gray-50">8. Third party rights</h3>
          <p>
            elbwalker is not responsible for the content provided by the user.
            In particular, elbwalker is not obliged to check the content for
            possible legal violations. As far as content is transmitted or made
            available, the user is responsible for ensuring that it is free of
            third party rights, in particular copyrights, naming and trademark
            rights that restrict or exclude use / processing in accordance with
            the scope agreed here. The processing of illegal, right-wing
            radical, pornographic, racist, immoral content is prohibited, as is
            the transmission of content that violates the decency of all those
            who think cheaply and justly. If a third party asserts claims
            against elbwalker that are based on the culpable violation of their
            property rights by the user, the user releases elbwalker from all
            costs and damages upon first request. In the event of a legal
            dispute, he bears all the necessary costs in this regard. The
            parties must immediately inform each other about the assertion of
            the claim by the third party.
          </p>
          <h3 className="text-gray-50">9. Prices / terms of payment</h3>
          <p>
            9.1 Unless otherwise agreed, prices are net in EURO plus statutory
            sales tax.
          </p>
          <p>
            9.2 Es gelten die zum Vertragsschluss gültigen Preise von elbwalker.
          </p>
          <p>
            9.3 Invoices are created electronically and sent by email. The
            remuneration is due upon receipt of the invoice and is payable
            within two weeks of the invoice date. The user hereby declares his /
            her consent.
          </p>
          <p>
            9.4 The remuneration is based on the commissioned service and the
            selected remuneration model.
          </p>
          <p>
            9.5 Billing takes place on the 1st of the calendar month for the
            previous month.
          </p>
          <p>
            9.6 If the user is in arrears with at least 2 monthly payments,
            elbwalker is entitled, after an unsuccessful reminder, to
            temporarily block access to elbwalker Analytics after a threat by
            e-mail until full payment has been made. elbwalker will inform the
            user of the announced date for the temporary blocking as part of the
            threat. The temporary blocking of services does not affect the
            user's payment obligation.
          </p>
          <h3 className="text-gray-50">10. Warranty and liability</h3>
          <p>
            10.1 The elbwalker warranty does not extend to damage and / or
            malfunctions caused by the user culpably violating the provisions of
            this contract. Upon request, the user will support elbwalker to the
            best of his ability in identifying and eliminating errors.
          </p>
          <p>
            10.2 If a defect occurs in the services provided by elbwalker,
            elbwalker will either remedy this within a reasonable period of time
            at its discretion or provide the service complained about again free
            of defects (overall subsequent performance).
          </p>
          <p>
            10.3 elbwalker has unlimited liability for damages or reimbursement
            of wasted expenses - in the event of willful intent or gross
            negligence, - for injury to life, limb or health, - in accordance
            with the provisions of the Product Liability Act and - within the
            scope of a guarantee assumed by elbwalker - in the event of
            fraudulent intent by elbwalker. The same applies in the event of a
            debtor's default by elbwalker for claims on default interest, on the
            default lump sum in accordance with Section 288 (5) of the German
            Civil Code (BGB) as well as on compensation for damage caused by
            default caused by the legal costs.
          </p>
          <p>
            10.4 In the event of a slightly negligent breach of an obligation
            that is essential for achieving the purpose of the contract
            (cardinal obligation), the amount of elbwalker's liability is
            limited to the damage that is foreseeable and typical for the type
            of business in question. The same applies in the event of default by
            elbwalker or the impossibility of rendering the service for which
            elbwalker is responsible.
          </p>
          <p>
            10.5 Liability for data loss is limited to the typical restoration
            effort that would have occurred if backup copies had been made
            regularly and in accordance with the risk, unless one of the
            prerequisites according to Section 10.3 applies. and 10.4. before.
          </p>
          <p>
            10.6 elbwalker is not liable for the functionality of the
            telecommunication connection (telephone / ISDN / DSL lines etc.) to
            its own server in the event of power failures or failures of servers
            that are beyond the control of elbwalker. Furthermore, elbwalker is
            not liable for damage caused by force majeure or comparable events.
            Strikes, pandemics, official orders, the failure of
            telecommunication networks or gateways of other operators as well as
            disruptions in the area of other telecommunication or service
            providers are considered comparable events.
          </p>
          <p>
            10.7 The liability of § 536 a, paragraph 2 of the German Civil Code
            (renter's right of removal) is excluded. The liability of elbwalker
            for damages (§ 536 a BGB) for defects existing at the time of the
            conclusion of the contract is also excluded, insofar as the standard
            provides for no-fault liability. Section 10.3. and 10.4. these terms
            of use remain unaffected.
          </p>
          <p>10.8 There is no further liability on the part of elbwalker.</p>
          <p>
            10.9 The above limitation of liability also applies to the personal
            liability of employees, representatives and organs of elbwalker.
          </p>
          <h3 className="text-gray-50">
            11. Data collection / confidentiality
          </h3>
          <p>
            11.1 Information on data collection by elbwalker can be found in the
            data protection notice at www.elbwalker.com/privacy and the scheme
            for collecting anonymized application data at
            www.elbwalker.com/docs/walkeros/event-model.
          </p>
          <p>
            11.2 The user declares that all personal data made available for
            processing within the scope of elbwalker Analytics has been lawfully
            transmitted to elbwalker Analytics in accordance with the applicable
            data protection law and may be processed by elbwalker Analytics. The
            user is prohibited from transmitting personal data of an end user to
            elbwalker Analytics without authorization or from having elbwalker
            Analytics process it.
          </p>
          <p>
            11.3 The user releases elbwalker from all claims by third parties
            due to data protection and personal rights violations that should be
            raised against elbwalker in connection with the processing of the
            personal data transmitted by the user to elbwalker Analytics, upon
            first request. The user is obliged to defend against unfounded
            claims by third parties with regard to the rights mentioned above.
            Any third-party claims that become known to the user must be
            reported to elbwalker immediately. The exemption also includes the
            reimbursement of costs that elbwalker incurs or has incurred through
            legal prosecution / defense. Any further claims for damages by
            elbwalker remain unaffected. Insofar as elbwalker is responsible for
            the infringement itself, claims against the user are excluded.
          </p>
          <p>
            11.4 The user is responsible for the permissibility of data
            processing. elbwalker supports the user insofar as data protection
            regulations provide for this. Further details on data processing are
            regulated in separate order processing contracts that elbwalker
            makes available for download.
          </p>
          <p>
            11.5 The parties undertake to keep confidential information from the
            other party confidential. This obligation also continues after the
            end of the contractual relationship. Confidential information that
            (a) It can be proven that the recipient already became aware of this
            when the contract was concluded or that it became known from a third
            party thereafter; (b) which are publicly known upon conclusion of
            the contract or are made publicly known thereafter; (c) which must
            be disclosed due to a legal obligation or by order of a court or an
            authority. As far as possible and permissible, the recipient obliged
            to disclose will inform the other party in advance and give them the
            opportunity to take action against the disclosure.
          </p>
          <h3 className="text-gray-50">
            12. Contract duration / termination / deletion of the user account
          </h3>
          <p>
            12.1 Contracts that are subject to a fee begin with the acceptance
            of the order by elbwalker. The minimum term is one month.
          </p>
          <p>
            12.2 The right to terminate for good cause remains unaffected.
            Important reasons are in particular - but not listed exhaustively:
            (a) the culpable breach of essential contractual obligations if,
            despite a warning, remedial action is not taken within a reasonable
            period of time; (b) Technical obstacles that were not foreseeable
            when the contract was concluded and which make the continuation of
            the services impossible.
          </p>
          <p>
            12.3 The right to terminate in accordance with Section 543 (2) No. 1
            BGB due to failure to use the contract in accordance with the
            contract is only permitted if elbwalker has been given sufficient
            opportunity to remedy the defect and this has failed.
          </p>
          <p>12.4 Terminations must be in text form (e.g. email).</p>
          <p>
            12.5 User accounts are closed upon termination of the contract. A
            final deletion of the account and the stored content and application
            data takes place 14 days after the end of the contract, unless the
            user deletes the account prematurely in the login area or extends
            the contract again within these 14 days.
          </p>
          <h3 className="text-gray-50">13. Subject to change</h3>
          <p>
            13.1 elbwalker reserves the right to unilaterally change these terms
            of use if this appears objectively justified. Changes are
            objectively justified, for example in the event of a change in the
            legal or legal situation (for example if the case law of a clause is
            declared ineffective) or if the equivalence relationship existing at
            the time the contract was concluded due to unforeseeable changes
            that elbwalker did not initiate and on which elbwalker also has no
            influence is disturbed to a not insignificant extent. A prerequisite
            for a change is always that it is reasonable for the user. The
            current version of the terms of use can be viewed and saved at
            www.elbwalker.com/terms.
          </p>
          <p>
            13.2 Registered users will be notified of changes to the terms of
            use. They are considered approved if the user has not objected to
            the validity of the changed terms of use within six weeks in writing
            or by e-mail to elbwalker and has informed elbwalker of the legal
            consequences of a failure to object.
          </p>
          <h3 className="text-gray-50">14. OS platform</h3>
          <p>
            The European Commission provides a platform for online dispute
            resolution (OS). The EU Commission's platform for online dispute
            resolution can be found here: www.ec.europa.eu/consumers/odr The
            provider's email address is: hello@elbwalker.com
          </p>
          <h3 className="text-gray-50">15. Final provisions</h3>
          <p>
            15.1 The contract text is saved by elbwalker and can be viewed at
            www.elbwalker.com/legal/terms.
          </p>
          <p>
            15.2 German law applies to the entire contractual relationship
            between elbwalker and the user, excluding UN sales law.
          </p>
          <p>
            15.3 The place of performance for all claims by elbwalker is the
            seat of elbwalker.
          </p>
          <p>
            15.4 Hamburg is deemed to be the agreed place of jurisdiction if the
            contracting parties are merchants, legal entities under public law
            or special funds under public law. However, elbwalker is also
            entitled to sue the user at his general place of jurisdiction. This
            does not apply if compulsory legal regulations within the meaning of
            Article 24, 25 or 26 EuGVVO in the version dated December 12, 2012
            conflict.
          </p>
          <p>
            15.5 Should a provision be wholly or partially ineffective or lose
            its legal validity later, this shall not affect the validity of the
            remaining provisions. If the contract contains a loophole, the same
            applies.
          </p>
          <p>STATUS February 2022</p>
        </div>
      </div>
    </div>
  );
}
