import type { ToolClient } from '../../tool-client.js';

export function stubClient(overrides: Partial<ToolClient> = {}): ToolClient {
  const notImpl = async () => {
    throw new Error('not implemented');
  };
  const base: ToolClient = {
    listProjects: notImpl,
    getProject: notImpl,
    createProject: notImpl,
    updateProject: notImpl,
    deleteProject: notImpl,
    setDefaultProject: () => {},
    getDefaultProject: () => null,
    listAllFlows: notImpl,
    listFlows: notImpl,
    getFlow: notImpl,
    createFlow: notImpl,
    updateFlow: notImpl,
    deleteFlow: notImpl,
    duplicateFlow: notImpl,
    listPreviews: notImpl,
    getPreview: notImpl,
    createPreview: notImpl,
    deletePreview: notImpl,
    listSecrets: notImpl,
    createSecret: notImpl,
    updateSecret: notImpl,
    deleteSecret: notImpl,
    deploy: notImpl,
    listDeployments: notImpl,
    getDeploymentBySlug: notImpl,
    deleteDeployment: notImpl,
    listJourneys: notImpl,
    listReleases: notImpl,
    getRelease: notImpl,
    listStepHistory: notImpl,
    setReleaseRationale: notImpl,
    listThreads: notImpl,
    createThread: notImpl,
    addThreadMessage: notImpl,
    listKnowledge: notImpl,
    listFrames: notImpl,
    listPageFrames: notImpl,
    getFrame: notImpl,
    requestDeviceCode: notImpl,
    pollForToken: notImpl,
    whoami: notImpl,
    credentialSource: () => null,
    logout: async () => ({ deleted: false }),
    checkHealth: async () => ({ reachable: true }),
    submitFeedback: notImpl,
    getFeedbackPreference: () => undefined,
    setFeedbackPreference: () => {},
  };
  return { ...base, ...overrides };
}
