/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/auth/magic-link': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Request magic link
     * @description Send a magic link to the provided email address for passwordless authentication. Always returns success to prevent email enumeration.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['MagicLinkRequest'];
        };
      };
      responses: {
        /** @description Magic link sent (or would be sent if email exists) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MagicLinkResponse'];
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/verify': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Verify magic link token
     * @description Verify a magic link token and create an authenticated session. Redirects to the specified URL or home page.
     */
    get: {
      parameters: {
        query: {
          /** @description Magic link token */
          token: string;
          /** @description Redirect URL after verification */
          redirect_to?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Redirect to target URL with session cookie set */
        302: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * End session
     * @description Destroy the current session and clear the session cookie.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Redirect to login page */
        302: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/whoami': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Current identity
     * @description Return the identity of the authenticated user. Supports session cookie and Bearer token.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Current user identity */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WhoamiResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List sessions
     * @description List all active sessions for the authenticated user. The current session is marked with isCurrent: true.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of active sessions */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ListSessionsResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/sessions/{sessionId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Revoke session
     * @description Revoke a session by ID. Cannot revoke the current session (use logout instead).
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          sessionId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Session revoked */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/device/code': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Request device code
     * @description Generate a device code and user code for the device authorization flow.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Device code generated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DeviceCodeResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/device/approve': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Approve device code
     * @description Approve a device authorization request using the user code. Requires authentication.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['ApproveDeviceRequest'];
        };
      };
      responses: {
        /** @description Device approved */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ApproveDeviceResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/device/token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Poll device token
     * @description Poll for authorization status using the device code. Returns a token when approved.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['DeviceTokenRequest'];
        };
      };
      responses: {
        /** @description Authorization approved */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DeviceTokenResponse'];
          };
        };
        /** @description Pending, slow down, or expired */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List my projects
     * @description List all projects where the authenticated user is a member.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of projects */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ListProjectsResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    /**
     * Create project
     * @description Create a new project. The authenticated user becomes the owner.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateProjectRequest'];
        };
      };
      responses: {
        /** @description Project created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CreateProjectResponse'];
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get project
     * @description Get a single project by ID. Requires membership.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Project details */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Project'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    /**
     * Delete project
     * @description Delete a project and all its resources. Requires owner role.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Project deleted */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    /**
     * Update project
     * @description Update project details. Requires owner role.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateProjectRequest'];
        };
      };
      responses: {
        /** @description Project updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Project'];
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    trace?: never;
  };
  '/api/projects/{projectId}/members': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List members
     * @description List all members of a project. Requires membership.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of members */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ListMembersResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    /**
     * Add member
     * @description Add a member to the project by email. Requires owner role.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['AddMemberRequest'];
        };
      };
      responses: {
        /** @description Member added */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Member'];
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}/members/{userId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Remove member
     * @description Remove a member from the project. Requires owner role.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
          userId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Member removed */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    /**
     * Update member role
     * @description Update a member's role. Requires owner role.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
          userId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateMemberRequest'];
        };
      };
      responses: {
        /** @description Role updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Member'];
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    trace?: never;
  };
  '/api/projects/{projectId}/flows': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List flows
     * @description List all flows for a project.
     */
    get: {
      parameters: {
        query?: {
          sort?: 'name' | 'updated_at' | 'created_at';
          order?: 'asc' | 'desc';
          include_deleted?: 'true' | 'false';
        };
        header?: never;
        path: {
          projectId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of flows */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ListFlowsResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    /**
     * Create flow
     * @description Create a new flow in the project. Requires owner role.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateFlowRequest'];
        };
      };
      responses: {
        /** @description Flow created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Flow'];
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}/flows/{flowId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get flow
     * @description Get a single flow by ID. Use ?fields to select specific sections (reduces response size).
     */
    get: {
      parameters: {
        query?: {
          /** @description Comma-separated dot-paths to select specific fields (e.g., "config.variables,config.flows.web.sources"). Always includes id, createdAt, updatedAt. */
          fields?: string;
        };
        header?: never;
        path: {
          projectId: string;
          flowId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Flow details */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['FlowDetailResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    /**
     * Soft-delete flow
     * @description Soft delete a flow (sets deleted_at timestamp). Requires owner role.
     */
    delete: {
      parameters: {
        query?: never;
        header?: {
          /** @description ETag from a previous GET. Returns 412 if flow was modified since. */
          'if-match'?: string;
        };
        path: {
          projectId: string;
          flowId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Flow deleted */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ETag mismatch — flow was modified since last read */
        412: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    /**
     * Update flow
     * @description Update an existing flow. Creates a version snapshot before applying changes. Requires owner role. Use Content-Type: application/merge-patch+json to send only changed fields (RFC 7386).
     */
    patch: {
      parameters: {
        query?: never;
        header?: {
          /** @description ETag from a previous GET. Returns 412 if flow was modified since. */
          'if-match'?: string;
        };
        path: {
          projectId: string;
          flowId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateFlowRequest'];
          'application/merge-patch+json': components['schemas']['UpdateFlowRequest'];
        };
      };
      responses: {
        /** @description Flow updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['FlowUpdateResponse'];
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description ETag mismatch — flow was modified since last read */
        412: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    trace?: never;
  };
  '/api/projects/{projectId}/flows/{flowId}/duplicate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Duplicate flow
     * @description Create a copy of an existing flow with a new ID and no version history. Requires owner role.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
          flowId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['DuplicateFlowRequest'];
        };
      };
      responses: {
        /** @description Flow duplicated */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Flow'];
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}/flows/{flowId}/deploy': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get latest deployment
     * @description Get the latest deployment for a flow.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
          flowId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Latest deployment (or null) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DeploymentResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    /**
     * Start deployment
     * @description Start a new deployment for a flow. Returns 400 AMBIGUOUS_SETTINGS if the flow has multiple named settings — use the per-settings deploy endpoint instead.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
          flowId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Deployment started */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['StartDeploymentResponse'];
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Deployment already in progress */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Service unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}/flows/{flowId}/deploy/{deploymentId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get deployment
     * @description Get a specific deployment by ID.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
          flowId: string;
          deploymentId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Deployment details */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DeploymentDetailResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    /**
     * Delete deployment
     * @description Delete a deployment and its container. Requires owner role.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
          flowId: string;
          deploymentId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Deployment deleted */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              id: string;
              /** @enum {string} */
              status: 'deleted';
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}/flows/{flowId}/deploy/{deploymentId}/advance': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Advance deployment
     * @description Advance the deployment state machine. Checks bundle/container status and transitions accordingly.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
          flowId: string;
          deploymentId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Current deployment state after advancement */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              id: string;
              flowId: string;
              /** @enum {string} */
              type: 'web' | 'server';
              status: string;
              containerUrl: string | null;
              publicUrl?: string | null;
              errorMessage: string | null;
              /** Format: date-time */
              createdAt: string;
              /** Format: date-time */
              updatedAt: string;
            };
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}/flows/{flowId}/settings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List settings
     * @description List active named settings for a flow.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
          flowId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of settings */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ListSettingsResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}/flows/{flowId}/settings/{settingsId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get settings
     * @description Get a single settings entry with its latest deployment.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
          flowId: string;
          settingsId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Settings details with deployment */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['FlowSettingsDetail'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}/flows/{flowId}/settings/{settingsId}/json': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Download settings JSON
     * @description Download the named flow settings as a self-contained Config JSON file. Includes parent variables.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
          flowId: string;
          settingsId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Flow Config JSON file */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['FlowConfig'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}/flows/{flowId}/settings/{settingsId}/bundle': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Download settings bundle
     * @description Download the compiled JS/MJS for the settings' latest deployment. Redirects to a presigned download URL.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
          flowId: string;
          settingsId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Redirect to presigned bundle URL */
        302: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Service unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}/flows/{flowId}/settings/{settingsId}/deploy': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get latest settings deployment
     * @description Get the latest deployment for a specific settings entry.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
          flowId: string;
          settingsId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Latest deployment (or null) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['SettingsDeploymentResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    /**
     * Deploy settings
     * @description Start a deployment for a specific settings entry. Detects platform from the settings.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
          flowId: string;
          settingsId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Deployment started */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DeploySettingsResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Deployment already in progress */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Settings orphaned */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Service unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}/flows/{flowId}/settings/{settingsId}/deployments/{deploymentId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get settings deployment detail
     * @description Get a specific deployment by ID, scoped to a settings entry.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
          flowId: string;
          settingsId: string;
          deploymentId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Deployment details */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['SettingsDeploymentDetailResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}/flows/{flowId}/settings/{settingsId}/deployments/{deploymentId}/advance': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Advance settings deployment
     * @description Advance the deployment state machine for a per-settings deployment.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
          flowId: string;
          settingsId: string;
          deploymentId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Current deployment state after advancement */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AdvanceSettingsDeploymentResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}/flows/{flowId}/versions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List versions
     * @description List all versions for a flow.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
          flowId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of versions */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ListVersionsResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}/flows/{flowId}/versions/{versionNumber}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get version
     * @description Get a specific version of a flow.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
          flowId: string;
          versionNumber: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Version details with content */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['GetVersionResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}/flows/{flowId}/versions/{versionNumber}/restore': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Restore version
     * @description Restore a flow to a specific version. Creates a new version snapshot. Requires owner role.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
          flowId: string;
          versionNumber: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Flow restored */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Flow'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/tokens': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List my tokens
     * @description List all API tokens for the authenticated user. Returns summaries (no raw token values).
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of tokens */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ListApiTokensResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    /**
     * Create token
     * @description Create a new API token. The raw token is returned once and cannot be retrieved again.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateApiTokenRequest'];
        };
      };
      responses: {
        /** @description Token created (raw token shown once) */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CreateApiTokenResponse'];
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/tokens/{tokenId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Revoke token
     * @description Revoke an API token (soft delete via revokedAt timestamp).
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          tokenId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Token revoked */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}/flows/{flowId}/bundle': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Trigger flow bundle
     * @description Start a bundle job for a project flow. For multi-settings flows, specify the named flow via ?flow= query parameter.
     */
    post: {
      parameters: {
        query?: {
          /** @description Named flow to bundle (required for multi-settings flows) */
          flow?: string;
        };
        header?: never;
        path: {
          projectId: string;
          flowId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Bundle job started */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['BundleJobResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Flow selection required for multi-settings flows */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Service unavailable */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}/flows/{flowId}/bundle/stream': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Stream bundle job status (SSE)
     * @description Stream bundle job progress via Server-Sent Events.
     */
    get: {
      parameters: {
        query: {
          jobId: string;
        };
        header?: never;
        path: {
          projectId: string;
          flowId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description SSE event stream */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}/flows/{flowId}/publish': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get publish status
     * @description Get the current publish status for a flow (CDN deployment).
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
          flowId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Publish status */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    /**
     * Publish flow to CDN
     * @description Publish a bundled flow to the CDN for client-side loading.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
          flowId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Flow published */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}/deployments/latest': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List latest deployments
     * @description List the latest deployment for each flow in the project.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Latest deployment per flow */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['LatestDeploymentsByFlow'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}/runtimes/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Register runtime
     * @description Register a server-side runtime container and get a presigned bundle URL.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['RegisterRuntimeRequest'];
        };
      };
      responses: {
        /** @description Presigned bundle URL */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}/observe/ticket': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create SSE ticket
     * @description Generate a one-time ticket for authenticating an SSE connection to the Observer service. Requires project membership.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Ticket generated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ObserveTicketResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}/observe/validate-ticket': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Validate ticket
     * @description Internal endpoint for the Observer service to validate and consume a ticket.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['ValidateTicketRequest'];
        };
      };
      responses: {
        /** @description Ticket payload */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ValidateTicketResponse'];
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Invalid or expired ticket */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health check
     * @description Check the health of the API and its dependencies.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Health status */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['HealthResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/openapi.json': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * OpenAPI spec
     * @description Return the OpenAPI 3.1 specification for this API.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OpenAPI document */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ingest/v1/{projectId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Event ingestion
     * @description Ingest walkerOS events for a project. Served by the Observer service (port 3001).
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Accepted */
        202: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/stream/v1': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * SSE stream
     * @description Server-Sent Events stream for real-time event observation. Requires a valid ticket. Served by the Observer service (port 3001).
     */
    get: {
      parameters: {
        query: {
          /** @description One-time ticket from /api/projects/{projectId}/observe/ticket */
          ticket: string;
          /** @description Project ID for scoped validation */
          project: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description SSE event stream */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Observer health
     * @description Health check for the Observer service (port 3001).
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Health status */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              status: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ErrorResponse: {
      error: {
        /** @example VALIDATION_ERROR */
        code: string;
        /** @example Validation failed */
        message: string;
        details?: {
          field?: string;
          reason?: string;
          errors?: {
            path: string;
            message: string;
          }[];
        } & {
          [key: string]: unknown;
        };
      };
    };
    FlowConfig: {
      /** @enum {number} */
      version: 4;
      $schema?: string;
      include?: string[];
      variables?: {
        [key: string]: unknown;
      };
      flows?: {
        [key: string]: unknown;
      };
      contract?: {
        [key: string]: unknown;
      };
    } & {
      [key: string]: unknown;
    };
    Flow: {
      /** @example flow_a1b2c3d4 */
      id: string;
      /** @example my-website-flow */
      name: string;
      config: components['schemas']['FlowConfig'];
      settings?: components['schemas']['FlowSettingsSummary'][];
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      updatedAt: string;
      /** Format: date-time */
      deletedAt?: string | null;
    };
    FlowSettingsSummary: {
      /** @example cfg_a1b2c3d4 */
      id: string;
      name: string;
      /**
       * @example web
       * @enum {string}
       */
      platform: 'web' | 'server';
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      updatedAt: string;
    };
    FlowSummary: {
      /** @example flow_a1b2c3d4 */
      id: string;
      /** @example my-website-flow */
      name: string;
      summary?: string;
      settings?: components['schemas']['FlowSettingsListItem'][];
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      updatedAt: string;
      /** Format: date-time */
      deletedAt: string | null;
    };
    FlowSettingsListItem: {
      /** @example cfg_a1b2c3d4 */
      id: string;
      name: string;
      /**
       * @example web
       * @enum {string}
       */
      platform: 'web' | 'server';
      deploymentStatus: string | null;
      deploymentUrl: string | null;
    };
    Version: {
      /** @example 1 */
      version: number;
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      createdAt: string;
      /**
       * @example user
       * @enum {string}
       */
      createdBy: 'user' | 'auto_save' | 'restore';
      /** @example sha256:abc123... */
      contentHash?: string;
    };
    Project: {
      /** @example proj_x7y8z9 */
      id: string;
      /** @example My Website */
      name: string;
      /**
       * @example owner
       * @enum {string}
       */
      role: 'owner' | 'admin' | 'member' | 'deployer' | 'viewer';
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      updatedAt: string;
    };
    Member: {
      userId: string;
      /** Format: email */
      email: string;
      /** @enum {string} */
      role: 'owner' | 'admin' | 'member' | 'deployer' | 'viewer';
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      createdAt: string;
    };
    ApiTokenSummary: {
      /** @example tok_a1b2c3d4 */
      id: string;
      /** @example CI Pipeline */
      name: string;
      /** @example sk-walkeros-abcd */
      prefix: string;
      /** @example manual */
      origin: string;
      /** @example null */
      projectId: string | null;
      /** @example null */
      scopes: string[] | null;
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      lastUsedAt: string | null;
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      expiresAt: string | null;
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      revokedAt: string | null;
    };
    FlowSettingsDetail: {
      /** @example cfg_a1b2c3d4 */
      id: string;
      name: string;
      /**
       * @example web
       * @enum {string}
       */
      platform: 'web' | 'server';
      config: {
        [key: string]: unknown;
      };
      deployment?: {
        id: string;
        status: string;
        type: string;
        containerUrl?: string | null;
        publicUrl?: string | null;
        errorMessage?: string | null;
        /**
         * Format: date-time
         * @example 2026-01-26T14:30:00.000Z
         */
        createdAt: string;
        /**
         * Format: date-time
         * @example 2026-01-26T14:30:00.000Z
         */
        updatedAt: string;
      } | null;
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      updatedAt: string;
    };
    DeploySettingsResponse: {
      deploymentId: string;
      /** @example cfg_a1b2c3d4 */
      settingsId: string;
      status: string;
    };
    FlowDetailResponse: {
      /** @example flow_a1b2c3d4 */
      id: string;
      /** @example my-website-flow */
      name: string;
      config: components['schemas']['FlowConfig'];
      settings?: components['schemas']['FlowSettingsEnriched'][];
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      updatedAt: string;
      /** Format: date-time */
      deletedAt: string | null;
    };
    FlowSettingsEnriched: {
      id: string;
      name: string;
      /** @enum {string} */
      platform: 'web' | 'server';
      deployment: {
        id: string;
        slug: string;
        status: string;
        type: string;
        target: string | null;
        containerUrl: string | null;
        /**
         * Format: date-time
         * @example 2026-01-26T14:30:00.000Z
         */
        createdAt: string;
        updatedAt: string | null;
      } | null;
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      updatedAt: string;
    };
    FlowUpdateResponse: {
      /** @example flow_a1b2c3d4 */
      id: string;
      /** @example my-website-flow */
      name: string;
      config: components['schemas']['FlowConfig'];
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      updatedAt: string;
    };
    CreateProjectResponse: {
      /** @example proj_x7y8z9 */
      id: string;
      name: string;
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      createdAt: string;
    };
    DeploymentSummary: {
      /** @example dep_a1b2c3d4 */
      id: string;
      /**
       * @example web
       * @enum {string}
       */
      type: 'web' | 'server';
      /** @example k7m2x9p4q1w8 */
      slug: string;
      target: string | null;
      label: string | null;
      /**
       * @example cloud
       * @enum {string}
       */
      origin: 'cloud' | 'self-hosted';
      /**
       * @example active
       * @enum {string}
       */
      status:
        | 'idle'
        | 'deploying'
        | 'published'
        | 'active'
        | 'stopped'
        | 'failed';
      currentVersionNumber: number | null;
      url: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      usageSummary?: {
        eventsIn24h: number;
        healthy: boolean;
      };
    };
    DeploymentDetailResponse: {
      /** @example dep_a1b2c3d4 */
      id: string;
      /**
       * @example web
       * @enum {string}
       */
      type: 'web' | 'server';
      /** @example k7m2x9p4q1w8 */
      slug: string;
      target: string | null;
      label: string | null;
      /**
       * @example cloud
       * @enum {string}
       */
      origin: 'cloud' | 'self-hosted';
      /**
       * @example active
       * @enum {string}
       */
      status:
        | 'idle'
        | 'deploying'
        | 'published'
        | 'active'
        | 'stopped'
        | 'failed';
      currentVersion: components['schemas']['DeploymentVersionDetail'];
      url: string | null;
      selfHosted: {
        /** Format: date-time */
        lastHeartbeatAt: string;
        instanceId: string | null;
        cliVersion: string | null;
        healthy: boolean;
      } | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    DeploymentVersionDetail: {
      number: number;
      status: string;
      source: {
        type: string;
        flowId?: string;
        flowSettingsId?: string;
        configHash?: string;
      };
      /** Format: date-time */
      publishedAt: string;
      publishedBy: string | null;
    } | null;
    CreateDeploymentResponse: {
      /** @example dep_a1b2c3d4 */
      id: string;
      /**
       * @example web
       * @enum {string}
       */
      type: 'web' | 'server';
      /** @example k7m2x9p4q1w8 */
      slug: string;
      target: string | null;
      label: string | null;
      /**
       * @example cloud
       * @enum {string}
       */
      origin: 'cloud' | 'self-hosted';
      /**
       * @example active
       * @enum {string}
       */
      status:
        | 'idle'
        | 'deploying'
        | 'published'
        | 'active'
        | 'stopped'
        | 'failed';
      currentVersionNumber: number | null;
      url: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      usageSummary?: {
        eventsIn24h: number;
        healthy: boolean;
      };
    };
    ListDeploymentsResponse: {
      deployments: components['schemas']['DeploymentSummary'][];
      total: number;
      limit: number;
      offset: number;
    };
    UpdateDeploymentResponse: {
      /** @example dep_a1b2c3d4 */
      id: string;
      /**
       * @example web
       * @enum {string}
       */
      type: 'web' | 'server';
      /** @example k7m2x9p4q1w8 */
      slug: string;
      target: string | null;
      label: string | null;
      /**
       * @example cloud
       * @enum {string}
       */
      origin: 'cloud' | 'self-hosted';
      /**
       * @example active
       * @enum {string}
       */
      status:
        | 'idle'
        | 'deploying'
        | 'published'
        | 'active'
        | 'stopped'
        | 'failed';
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    LatestDeploymentsByFlow: {
      [key: string]: {
        id: string;
        flowId: string;
        slug: string;
        type: string;
        status: string;
        target: string | null;
        containerUrl: string | null;
        createdAt: string;
      };
    };
    PublishVersionResponse: {
      versionNumber: number;
      versionId: string;
      /** @example dep_a1b2c3d4 */
      deploymentId: string;
      /** @enum {string} */
      status: 'deploying';
      source:
        | {
            /** @enum {string} */
            type: 'flow';
            flowId: string;
            flowSettingsName: string;
          }
        | {
            /** @enum {string} */
            type: 'config';
          };
      /** Format: date-time */
      createdAt: string;
    };
    ListDeploymentVersionsResponse: {
      versions: {
        number: number;
        status: string;
        source: {
          type: string;
          flowId?: string;
          flowSettingsId?: string;
          configHash?: string;
        };
        bundlePath: string | null;
        /** Format: date-time */
        publishedAt: string;
        publishedBy: string | null;
      }[];
      total: number;
      limit: number;
      offset: number;
    };
    HeartbeatResponse: {
      /** @enum {boolean} */
      ack: true;
      /** @example dep_a1b2c3d4 */
      deploymentId: string;
      /** @enum {string} */
      action: 'none' | 'stop' | 'update';
      versionNumber?: number;
      bundleUrl?: string;
    };
    ObserveTicketResponse: {
      ticket: string;
      /** Format: uri */
      observerUrl: string;
    };
    MagicLinkResponse: {
      /** @example true */
      success: boolean;
      /** @example Magic link sent */
      message: string;
    };
    MagicLinkRequest: {
      /**
       * Format: email
       * @example user@example.com
       */
      email: string;
      /** @example /dashboard */
      redirect_to?: string;
    };
    WhoamiResponse: {
      /** @example user_a1b2c3d4 */
      userId: string;
      /**
       * Format: email
       * @example user@example.com
       */
      email: string;
      /** @example null */
      projectId: string | null;
    };
    ListSessionsResponse: {
      sessions: {
        id: string;
        /** Format: date-time */
        createdAt: string;
        /** Format: date-time */
        expiresAt: string;
        /** Format: date-time */
        lastTouchedAt: string;
        isCurrent: boolean;
      }[];
    };
    DeviceCodeResponse: {
      deviceCode: string;
      userCode: string;
      expiresIn: number;
      interval: number;
    };
    ApproveDeviceResponse: {
      success: boolean;
    };
    ApproveDeviceRequest: {
      userCode: string;
    };
    DeviceTokenResponse: {
      token: string;
      email: string;
      userId: string;
    };
    DeviceTokenRequest: {
      deviceCode: string;
      hostname?: string;
    };
    ListProjectsResponse: {
      projects: components['schemas']['Project'][];
      total: number;
    };
    CreateProjectRequest: {
      name: string;
    };
    UpdateProjectRequest: {
      name?: string;
    };
    ListMembersResponse: {
      members: components['schemas']['Member'][];
      total: number;
    };
    AddMemberRequest: {
      /**
       * Format: email
       * @example user@example.com
       */
      email: string;
      /**
       * @default member
       * @enum {string}
       */
      role: 'owner' | 'admin' | 'member' | 'deployer' | 'viewer';
    };
    UpdateMemberRequest: {
      /** @enum {string} */
      role: 'owner' | 'admin' | 'member' | 'deployer' | 'viewer';
    };
    ListFlowsResponse: {
      flows: components['schemas']['FlowSummary'][];
      total: number;
    };
    CreateFlowRequest: {
      /** @example my-website-flow */
      name: string;
      config?: components['schemas']['FlowConfig'];
    };
    UpdateFlowRequest: {
      /** @example my-website-flow */
      name?: string;
      config?: components['schemas']['FlowConfig'];
    };
    DuplicateFlowRequest: {
      /** @example my-website-flow */
      name?: string;
    };
    DeploymentResponse: {
      id: string;
      flowId: string;
      /** @enum {string} */
      type: 'web' | 'server';
      status: string;
      containerUrl: string | null;
      publicUrl?: string | null;
      errorMessage: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    } | null;
    StartDeploymentResponse: {
      deploymentId: string;
      /** @enum {string} */
      type: 'web' | 'server';
      status: string;
    };
    ListSettingsResponse: {
      settings: components['schemas']['FlowSettingsSummary'][];
    };
    SettingsDeploymentResponse: {
      id: string;
      flowId: string;
      settingsId: string;
      /** @enum {string} */
      type: 'web' | 'server';
      status: string;
      containerUrl: string | null;
      publicUrl: string | null;
      errorMessage: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    } | null;
    SettingsDeploymentDetailResponse: {
      id: string;
      flowId: string;
      settingsId: string;
      status: string;
      /** @enum {string} */
      type: 'web' | 'server';
      containerUrl: string | null;
      publicUrl: string | null;
      errorMessage: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    AdvanceSettingsDeploymentResponse: {
      id: string;
      flowId: string;
      /** @enum {string} */
      type: 'web' | 'server';
      status: string;
      containerUrl: string | null;
      publicUrl?: string | null;
      errorMessage: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    ListVersionsResponse: {
      data: components['schemas']['Version'][];
      /** @example flow_a1b2c3d4 */
      flowId: string;
      total: number;
    };
    GetVersionResponse: {
      /** @example 1 */
      version: number;
      content: components['schemas']['FlowConfig'];
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      createdAt: string;
      /** @enum {string} */
      createdBy: 'user' | 'auto_save' | 'restore';
    };
    ListApiTokensResponse: {
      tokens: components['schemas']['ApiTokenSummary'][];
    };
    CreateApiTokenResponse: {
      /** @example tok_a1b2c3d4 */
      id: string;
      /** @example CI Pipeline */
      name: string;
      /** @example sk-walkeros-abcd1234... */
      token: string;
      /** @example sk-walkeros-abcd */
      prefix: string;
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      expiresAt: string | null;
      /** @example null */
      projectId: string | null;
    };
    CreateApiTokenRequest: {
      /** @example CI Pipeline */
      name: string;
      /** @example 90 */
      expiresInDays?: number | null;
    };
    BundleJobResponse: {
      jobId: string;
      state: string;
      hash: string;
      bundlePath: string;
    };
    RegisterRuntimeRequest: {
      flowId: string;
      bundlePath: string;
    };
    ValidateTicketResponse: {
      userId: string;
      projectId: string;
      replay: {
        size: number;
        ttlMs: number;
      };
    };
    ValidateTicketRequest: {
      ticket: string;
    };
    HealthResponse: {
      /** @example ok */
      status: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
