/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/auth/magic-link': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Request magic link
     * @description Send a magic link to the provided email address for passwordless authentication. Always returns success to prevent email enumeration.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['MagicLinkRequest'];
        };
      };
      responses: {
        /** @description Magic link sent (or would be sent if email exists) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['MagicLinkResponse'];
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/verify': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Verify magic link token
     * @description Verify a magic link token and create an authenticated session. Redirects to the specified URL or home page.
     */
    get: {
      parameters: {
        query: {
          /** @description Magic link token */
          token: string;
          /** @description Redirect URL after verification */
          redirect_to?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Redirect to target URL with session cookie set */
        302: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * End session
     * @description Destroy the current session and clear the session cookie.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Redirect to login page */
        302: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/auth/whoami': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Current identity
     * @description Return the identity of the authenticated user. Supports session cookie and Bearer token.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Current user identity */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['WhoamiResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List my projects
     * @description List all projects where the authenticated user is a member.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of projects */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ListProjectsResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    /**
     * Create project
     * @description Create a new project. The authenticated user becomes the owner.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateProjectRequest'];
        };
      };
      responses: {
        /** @description Project created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Project'];
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get project
     * @description Get a single project by ID. Requires membership.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Project details */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Project'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    /**
     * Delete project
     * @description Delete a project and all its resources. Requires owner role.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Project deleted */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    /**
     * Update project
     * @description Update project details. Requires owner role.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateProjectRequest'];
        };
      };
      responses: {
        /** @description Project updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Project'];
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    trace?: never;
  };
  '/api/projects/{projectId}/members': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List members
     * @description List all members of a project. Requires membership.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of members */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ListMembersResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    /**
     * Add member
     * @description Add a member to the project by email. Requires owner role.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['AddMemberRequest'];
        };
      };
      responses: {
        /** @description Member added */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Member'];
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}/members/{userId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Remove member
     * @description Remove a member from the project. Requires owner role.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
          userId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Member removed */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    /**
     * Update member role
     * @description Update a member's role. Requires owner role.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
          userId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateMemberRequest'];
        };
      };
      responses: {
        /** @description Role updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Member'];
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    trace?: never;
  };
  '/api/projects/{projectId}/flows': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List flows
     * @description List all flows for a project.
     */
    get: {
      parameters: {
        query?: {
          sort?: 'name' | 'updated_at' | 'created_at';
          order?: 'asc' | 'desc';
          include_deleted?: 'true' | 'false';
        };
        header?: never;
        path: {
          projectId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of flows */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ListFlowsResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    /**
     * Create flow
     * @description Create a new flow in the project. Requires owner role.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateFlowRequest'];
        };
      };
      responses: {
        /** @description Flow created */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Flow'];
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}/flows/{flowId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get flow
     * @description Get a single flow by ID.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
          flowId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Flow details */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Flow'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    /**
     * Soft-delete flow
     * @description Soft delete a flow (sets deleted_at timestamp). Requires owner role.
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
          flowId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Flow deleted */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    /**
     * Update flow
     * @description Update an existing flow. Creates a version snapshot before applying changes. Requires owner role.
     */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
          flowId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['UpdateFlowRequest'];
        };
      };
      responses: {
        /** @description Flow updated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Flow'];
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    trace?: never;
  };
  '/api/projects/{projectId}/flows/{flowId}/duplicate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Duplicate flow
     * @description Create a copy of an existing flow with a new ID and no version history. Requires owner role.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
          flowId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['DuplicateFlowRequest'];
        };
      };
      responses: {
        /** @description Flow duplicated */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Flow'];
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}/flows/{flowId}/versions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List versions
     * @description List all versions for a flow.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
          flowId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of versions */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ListVersionsResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}/flows/{flowId}/versions/{versionNumber}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get version
     * @description Get a specific version of a flow.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
          flowId: string;
          versionNumber: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Version details with content */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['GetVersionResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}/flows/{flowId}/versions/{versionNumber}/restore': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Restore version
     * @description Restore a flow to a specific version. Creates a new version snapshot. Requires owner role.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
          flowId: string;
          versionNumber: number;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Flow restored */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Flow'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/tokens': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List my tokens
     * @description List all API tokens for the authenticated user. Returns summaries (no raw token values).
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description List of tokens */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ListApiTokensResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    /**
     * Create token
     * @description Create a new API token. The raw token is returned once and cannot be retrieved again.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['CreateApiTokenRequest'];
        };
      };
      responses: {
        /** @description Token created (raw token shown once) */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CreateApiTokenResponse'];
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/tokens/{tokenId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Revoke token
     * @description Revoke an API token (soft delete via revokedAt timestamp).
     */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          tokenId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Token revoked */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/bundle': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Bundle flow
     * @description Bundle a walkerOS flow into a deployable JavaScript module.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      /** @description Flow content to bundle */
      requestBody?: {
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
      responses: {
        /** @description Bundled JavaScript module */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/javascript': string;
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Payload too large */
        413: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}/flows/{flowId}/deploy': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get latest deployment
     * @description Get the latest deployment for a flow.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
          flowId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Latest deployment (or null) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Deployment'] | null;
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    /**
     * Deploy flow
     * @description Start a deployment for a flow. Auto-detects web or server from flow content.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
          flowId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Deployment started */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['DeployResponse'];
          };
        };
        /** @description Invalid flow */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}/flows/{flowId}/deploy/{deploymentId}/advance': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Advance deployment
     * @description Advance the deployment state machine. Poll until terminal status.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
          flowId: string;
          deploymentId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Current deployment state */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Deployment'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}/observe/ticket': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create SSE ticket
     * @description Generate a one-time ticket for authenticating an SSE connection to the Observer service. Requires project membership.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Ticket generated */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['CreateTicketResponse'];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/projects/{projectId}/observe/validate-ticket': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Validate ticket
     * @description Internal endpoint for the Observer service to validate and consume a ticket.
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': components['schemas']['ValidateTicketRequest'];
        };
      };
      responses: {
        /** @description Ticket payload */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ValidateTicketResponse'];
          };
        };
        /** @description Validation error */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Invalid or expired ticket */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
        /** @description Forbidden */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health check
     * @description Check the health of the API and its dependencies.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Health status */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['HealthResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/openapi.json': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * OpenAPI spec
     * @description Return the OpenAPI 3.1 specification for this API.
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OpenAPI document */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              [key: string]: unknown;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/ingest/v1/{projectId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Event ingestion
     * @description Ingest walkerOS events for a project. Served by the Observer service (port 3001).
     */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          projectId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Accepted */
        202: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/stream/v1': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * SSE stream
     * @description Server-Sent Events stream for real-time event observation. Requires a valid ticket. Served by the Observer service (port 3001).
     */
    get: {
      parameters: {
        query: {
          /** @description One-time ticket from /api/projects/{projectId}/observe/ticket */
          ticket: string;
          /** @description Project ID for scoped validation */
          project: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description SSE event stream */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ErrorResponse'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Observer health
     * @description Health check for the Observer service (port 3001).
     */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Health status */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              status: string;
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ErrorResponse: {
      error: {
        /** @example VALIDATION_ERROR */
        code: string;
        /** @example Validation failed */
        message: string;
        details?: {
          field?: string;
          reason?: string;
          errors?: {
            path: string;
            message: string;
          }[];
        } & {
          [key: string]: unknown;
        };
      };
    };
    FlowContent: {
      /** @enum {number} */
      version: 1;
      $schema?: string;
      include?: string[];
      variables?: {
        [key: string]: string | number | boolean;
      };
      definitions?: {
        [key: string]: unknown;
      };
      flows?: {
        [key: string]: unknown;
      };
    };
    Flow: {
      /** @example flow_a1b2c3d4 */
      id: string;
      /** @example my-website-flow */
      name: string;
      content: components['schemas']['FlowContent'];
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      updatedAt: string;
      /** Format: date-time */
      deletedAt?: string | null;
    };
    FlowSummary: {
      /** @example flow_a1b2c3d4 */
      id: string;
      /** @example my-website-flow */
      name: string;
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      updatedAt: string;
      /** Format: date-time */
      deletedAt: string | null;
    };
    Version: {
      /** @example 1 */
      version: number;
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      createdAt: string;
      /**
       * @example user
       * @enum {string}
       */
      createdBy: 'user' | 'auto_save' | 'restore';
      /** @example sha256:abc123... */
      contentHash?: string;
    };
    Project: {
      /** @example proj_x7y8z9 */
      id: string;
      /** @example My Website */
      name: string;
      /**
       * @example owner
       * @enum {string}
       */
      role: 'owner' | 'member';
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      updatedAt: string;
    };
    Member: {
      userId: string;
      /** Format: email */
      email: string;
      /** @enum {string} */
      role: 'owner' | 'member';
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      createdAt: string;
    };
    ApiTokenSummary: {
      /** @example tok_a1b2c3d4 */
      id: string;
      /** @example CI Pipeline */
      name: string;
      /** @example sk-walkeros-abcd */
      prefix: string;
      /** @example null */
      projectId: string | null;
      /** @example null */
      scopes: string[] | null;
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      lastUsedAt: string | null;
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      expiresAt: string | null;
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      revokedAt: string | null;
    };
    MagicLinkResponse: {
      /** @example true */
      success: boolean;
      /** @example Magic link sent */
      message: string;
    };
    MagicLinkRequest: {
      /**
       * Format: email
       * @example user@example.com
       */
      email: string;
      /**
       * Format: uri
       * @example /dashboard
       */
      redirect_to?: string;
    };
    WhoamiResponse: {
      /** @example user_a1b2c3d4 */
      userId: string;
      /**
       * Format: email
       * @example user@example.com
       */
      email: string;
      /** @example null */
      projectId: string | null;
    };
    ListProjectsResponse: {
      projects: components['schemas']['Project'][];
      total: number;
    };
    CreateProjectRequest: {
      name: string;
    };
    UpdateProjectRequest: {
      name?: string;
    };
    ListMembersResponse: {
      members: components['schemas']['Member'][];
      total: number;
    };
    AddMemberRequest: {
      /**
       * Format: email
       * @example user@example.com
       */
      email: string;
      /**
       * @default member
       * @enum {string}
       */
      role: 'owner' | 'member';
    };
    UpdateMemberRequest: {
      /** @enum {string} */
      role: 'owner' | 'member';
    };
    ListFlowsResponse: {
      flows: components['schemas']['FlowSummary'][];
      total: number;
    };
    CreateFlowRequest: {
      /** @example my-website-flow */
      name: string;
      content?: components['schemas']['FlowContent'];
    };
    UpdateFlowRequest: {
      /** @example my-website-flow */
      name?: string;
      content?: components['schemas']['FlowContent'];
    };
    DuplicateFlowRequest: {
      /** @example my-website-flow */
      name?: string;
    };
    ListVersionsResponse: {
      data: components['schemas']['Version'][];
      /** @example flow_a1b2c3d4 */
      flowId: string;
      total: number;
    };
    GetVersionResponse: {
      /** @example 1 */
      version: number;
      content: components['schemas']['FlowContent'];
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      createdAt: string;
      /** @enum {string} */
      createdBy: 'user' | 'auto_save' | 'restore';
    };
    ListApiTokensResponse: {
      tokens: components['schemas']['ApiTokenSummary'][];
    };
    CreateApiTokenResponse: {
      /** @example tok_a1b2c3d4 */
      id: string;
      /** @example CI Pipeline */
      name: string;
      /** @example sk-walkeros-abcd1234... */
      token: string;
      /** @example sk-walkeros-abcd */
      prefix: string;
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      createdAt: string;
      /**
       * Format: date-time
       * @example 2026-01-26T14:30:00.000Z
       */
      expiresAt: string | null;
      /** @example null */
      projectId: string | null;
    };
    CreateApiTokenRequest: {
      /** @example CI Pipeline */
      name: string;
      /** @example 90 */
      expiresInDays?: number | null;
    };
    CreateTicketResponse: {
      /** @example tkt_abc123... */
      ticket: string;
      /**
       * Format: uri
       * @example http://localhost:3001
       */
      observerUrl: string;
    };
    ValidateTicketResponse: {
      userId: string;
      projectId: string;
      replay: {
        size: number;
        ttlMs: number;
      };
    };
    ValidateTicketRequest: {
      ticket: string;
    };
    Deployment: {
      /** @example dep_a1b2c3d4 */
      id: string;
      /** @example flow_a1b2c3d4 */
      flowId: string;
      /** @enum {string} */
      type: 'web' | 'server';
      /** @enum {string} */
      status:
        | 'bundling'
        | 'deploying'
        | 'active'
        | 'failed'
        | 'deleted'
        | 'published';
      containerUrl?: string | null;
      publicUrl?: string | null;
      scriptTag?: string | null;
      errorMessage?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    DeployResponse: {
      /** @example dep_a1b2c3d4 */
      deploymentId: string;
      /** @enum {string} */
      type: 'web' | 'server';
      /** @example bundling */
      status: string;
    };
    HealthResponse: {
      /** @example ok */
      status: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
