import path from 'path';
import fs from 'fs-extra';
import type { Logger } from '@walkeros/core';

export function buildDockerfileContent(
  platform: 'web' | 'server',
  includedFolders: string[],
): string {
  const bundleFile = platform === 'web' ? 'walker.js' : 'bundle.mjs';

  const lines = [
    '# Generated by walkeros CLI',
    'FROM walkeros/flow:latest',
    '',
    `COPY ${bundleFile} /app/flow/${bundleFile}`,
  ];

  for (const folder of includedFolders) {
    const name = path.basename(folder);
    lines.push(`COPY ${name}/ /app/flow/${name}/`);
  }

  lines.push('', `ENV BUNDLE=/app/flow/${bundleFile}`, '', 'EXPOSE 8080', '');

  return lines.join('\n');
}

export async function generateDockerfile(
  outputDir: string,
  platform: 'web' | 'server',
  logger: Logger.Instance,
  customFile?: string,
  includedFolders?: string[],
): Promise<void> {
  const destPath = path.join(outputDir, 'Dockerfile');

  // Copy mode: use custom file if it exists
  if (customFile && (await fs.pathExists(customFile))) {
    await fs.copy(customFile, destPath);
    logger.info(`Dockerfile: ${destPath} (copied from ${customFile})`);
    return;
  }

  // Generate mode
  const dockerfile = buildDockerfileContent(platform, includedFolders || []);
  await fs.writeFile(destPath, dockerfile);
  logger.info(`Dockerfile: ${destPath}`);
}
