import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    // Mixed approach: autogenerated with specific Sources override
    {
      type: 'category',
      label: 'Getting started',
      collapsed: false,
      items: [{ type: 'autogenerated', dirName: 'getting-started' }],
    },
    {
      type: 'category',
      label: 'Sources',
      link: {
        type: 'doc',
        id: 'sources/index',
      },
      items: [
        {
          type: 'category',
          label: 'Browser',
          link: {
            type: 'doc',
            id: 'sources/web/browser/index',
          },
          items: [
            'sources/web/browser/commands',
            'sources/web/browser/tagging',
            'sources/web/browser/tagger',
          ],
        },
        'sources/web/dataLayer/index',
        'sources/server/express',
        'sources/server/fetch',
        'sources/server/aws',
        'sources/server/gcp',
        'sources/create-your-own',
      ],
    },
    {
      type: 'category',
      label: 'Collector',
      link: {
        type: 'doc',
        id: 'collector/index',
      },
      items: ['collector/commands'],
    },
    'mapping',
    {
      type: 'category',
      label: 'Destinations',
      link: {
        type: 'doc',
        id: 'destinations/index',
      },
      items: [
        // Web destinations - flattened
        'destinations/web/api',
        {
          type: 'category',
          label: 'Google tag (gtag)',
          link: {
            type: 'doc',
            id: 'destinations/web/gtag/index',
          },
          items: [
            'destinations/web/gtag/ga4',
            'destinations/web/gtag/ads',
            'destinations/web/gtag/gtm',
          ],
        },
        'destinations/web/meta-pixel',
        'destinations/web/piwikpro',
        'destinations/web/plausible',
        // Server destinations - flattened
        'destinations/server/aws',
        'destinations/server/gcp',
        'destinations/server/meta-capi',
        'destinations/create-your-own',
      ],
    },
    {
      type: 'category',
      label: 'Core',
      link: {
        type: 'doc',
        id: 'core/index',
      },
      items: ['core/web', 'core/server'],
    },
    {
      type: 'category',
      label: 'Apps',
      link: {
        type: 'doc',
        id: 'apps/index',
      },
      items: ['apps/walkerjs', 'apps/cli', 'apps/docker'],
    },
    {
      type: 'category',
      label: 'Guides',
      link: {
        type: 'doc',
        id: 'guides/index',
      },
      items: [
        {
          type: 'category',
          label: 'Consent',
          link: {
            type: 'doc',
            id: 'guides/consent/index',
          },
          items: [
            { type: 'autogenerated', dirName: 'guides/consent/examples' },
          ],
        },
        'guides/session',
        'guides/user-stitching',
        'guides/migration',
      ],
    },
    {
      type: 'category',
      label: 'Comparisons',
      link: {
        type: 'doc',
        id: 'comparisons/index',
      },
      items: ['comparisons/dataLayer'],
    },
    'contributing',
  ],
};

export default sidebars;
