import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    // Mixed approach: autogenerated with specific Sources override
    {
      type: 'category',
      label: 'What is walkerOS',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'getting-started/index',
      },
      items: [
        {
          type: 'category',
          label: 'Getting started',
          items: [
            { type: 'autogenerated', dirName: 'getting-started/quickstart' },
          ],
        },
        {
          type: 'category',
          label: 'Operating modes',
          link: {
            type: 'doc',
            id: 'getting-started/modes/index',
          },
          items: [
            'getting-started/modes/bundled',
            'getting-started/modes/integrated',
          ],
        },
        'getting-started/flow',
        'getting-started/event-model',
      ],
    },
    {
      type: 'category',
      label: 'Sources',
      link: {
        type: 'doc',
        id: 'sources/index',
      },
      items: [
        {
          type: 'category',
          label: 'Browser',
          link: {
            type: 'doc',
            id: 'sources/web/browser/index',
          },
          items: [
            'sources/web/browser/commands',
            {
              type: 'category',
              label: 'Tagging',
              items: [
                'sources/web/browser/tagging/html-attributes',
                'sources/web/browser/tagging/javascript',
              ],
            },
            'sources/web/browser/tagger',
          ],
        },
        'sources/web/dataLayer/index',
        'sources/server/express',
        'sources/server/fetch',
        'sources/server/aws',
        'sources/server/gcp',
        'sources/create-your-own',
      ],
    },
    {
      type: 'category',
      label: 'Collector',
      link: {
        type: 'doc',
        id: 'collector/index',
      },
      items: ['collector/commands'],
    },
    {
      type: 'category',
      label: 'Transformers',
      link: {
        type: 'doc',
        id: 'transformers/index',
      },
      items: [
        'transformers/validator',
        'transformers/router',
        'transformers/create-your-own',
      ],
    },
    'mapping',
    {
      type: 'category',
      label: 'Destinations',
      link: {
        type: 'doc',
        id: 'destinations/index',
      },
      items: [
        // API destination (web + server)
        {
          type: 'category',
          label: 'API',
          link: {
            type: 'doc',
            id: 'destinations/api/index',
          },
          items: ['destinations/api/web', 'destinations/api/server'],
        },
        {
          type: 'category',
          label: 'Google tag (gtag)',
          link: {
            type: 'doc',
            id: 'destinations/web/gtag/index',
          },
          items: [
            'destinations/web/gtag/ga4',
            'destinations/web/gtag/ads',
            'destinations/web/gtag/gtm',
          ],
        },
        'destinations/web/meta-pixel',
        'destinations/web/piwikpro',
        'destinations/web/plausible',
        // Server destinations - flattened
        'destinations/server/aws',
        'destinations/server/gcp',
        'destinations/server/meta-capi',
        'destinations/create-your-own',
      ],
    },
    {
      type: 'category',
      label: 'Core',
      link: {
        type: 'doc',
        id: 'core/index',
      },
      items: ['core/web', 'core/server'],
    },
    {
      type: 'category',
      label: 'Apps',
      link: {
        type: 'doc',
        id: 'apps/index',
      },
      items: [
        'apps/walkerjs',
        'apps/cli',
        'apps/mcp',
        'apps/docker',
        'apps/storybook',
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      link: {
        type: 'doc',
        id: 'guides/index',
      },
      items: [
        {
          type: 'category',
          label: 'Consent',
          link: {
            type: 'doc',
            id: 'guides/consent/index',
          },
          items: [
            { type: 'autogenerated', dirName: 'guides/consent/examples' },
          ],
        },
        'guides/session',
        'guides/user-stitching',
        'guides/migration',
      ],
    },
    {
      type: 'category',
      label: 'Comparisons',
      link: {
        type: 'doc',
        id: 'comparisons/index',
      },
      items: [
        'comparisons/dataLayer',
        'comparisons/gtm',
        'comparisons/jentis',
        'comparisons/jitsu',
        'comparisons/rudderstack',
        'comparisons/segment',
        'comparisons/snowplow',
        'comparisons/stape',
      ],
    },
    'contributing',
  ],
};

export default sidebars;
